import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>FlashTyping</title>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <Toaster toastOptions={{
            className: '',
            style: {
              color:"white",
              background:'#ffffff21',
              borderRadius: '16px',
              boxShadow:'0 4px 30px rgba(0, 0, 0, 0.1)',
              backdropFilter:'blur(5px)',
              WebkitBackdropFilter:'blur(5px)',
              border:'1px solid rgba(255, 255, 255, 0.02)'
            },
  }}
/>
      </body>
    </html>
  );
}
